name: "Determine Version"
description: "Calculates the version tag based off the git reference. SemVer tags are presevered, default branch is latest, other branch are untouched, PRs output alternate ID"
inputs:
  old-version:
    description: "The current reference point for the version"
    required: false
    default: "1.0.0-dev.1"
  new-version:
    description: "The version to insert into the files"
    required: true
  target-file:
    description: "The file which needs to be modified"
    required: true
runs:
  using: "composite"
  steps:
    - run: sed -i "s/${{ inputs.old-version }}/${{ inputs.new-version }}/1" ${{ inputs.target-file }}
      shell: bash
