name: 'Setup Conan'
description: 'Install and configure the conan client and setup caching of the .conan/'
inputs:
  libcxx:
    description: 'C++ standard ABI version to use'
    required: false
    default: 'libstdc++11'
outputs:
  random-number: 
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
runs:
  using: "composite"
  steps: 
    - id: random-number-generator
      run: echo "::set-output name=random-id::$(echo $RANDOM)"
      shell: bash
    - runs:
      using: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: python -m pip install --upgrade pip conan
      shell: bash
    - run: conan profile new default --detect
      shell: bash
    - run: conan profile update settings.compiler.libcxx=${{ inputs.libcxx }} default
      shell: bash
