name: 'Determine Version'
description: 'Calculates the version tag based off the action and git/ref'
inputs:
  github-ref:
    description: 'The current reference point for the version'
    required: true
outputs:
  build-version: 
    description: "Build Version"
    value: ${{ steps.cal.outputs.build-version }}
runs:
  using: "composite"
  steps: 
    - run: VERSION=$(echo "${{ inputs.github-ref }}" | sed -e 's,.*/\(.*\),\1,') # Strip git ref prefix from version
      shell: bash
    - run: |
        [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//') # Strip "v" prefix from tag name
      shell: bash
    - run: |
        [ "$VERSION" == "master" ] && VERSION=latest  # Use Docker `latest` tag convention
      shell: bash
    - id: cal
      run: echo "::set-output name=build-version::$(echo $VERSION)"
      shell: bash
