name: 'Determine Version'
description: 'Calculates the version tag based off the git reference. SemVer tags are presevered, default branch is latest, other branch are untouched, PRs output merge'
inputs:
  github-ref:
    description: 'The current reference point for the version'
    required: true
outputs:
  build-version: 
    description: "Build Version"
    value: ${{ steps.cal.outputs.version }}
runs:
  using: "composite"
  steps:
  - id: cal
    run: |
      VERSION=$(echo "${{ inputs.github-ref }}" | sed -e 's,.*/\(.*\),\1,')
      [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
      [ "$VERSION" == "master" ] && VERSION=latest
      echo "::set-output name=version::$(echo $VERSION)"
    shell: bash
