openapi: "3.0.0"
info:
  title: User Management API
  version: "1.0.0-dev"
  description: >-
    A Simple API for creating, editing, and deleting
    users. The goal here is to offer minimal flexability
    that is sufficient for demonstrating a backend server
    or database integration.

servers:
  - url: "{server}/um/v1"
    variables:
      server:
        default: https://api.example.com
        enum:
        - https://api.example.com
        - https://ec2-3-14-64-10.us-east-2.compute.amazonaws.com/

tags:
  - name: Search
    description: Searching database of users
  - name: Edit
    description: Edit user's entry in database
  - name: CORS
    description: Preflight requests to support CORS

components:
  parameters:
    id:
      name: id
      in: path
      required: true
      description: ID of the resoective user to display
      schema:
        type: integer
      example: 15
  schemas:
    User:
      $ref: "./schema/user.json"
    Users:
      $ref: "./schema/users.json"
    Add:
      $ref: "./schema/add.json"
    Edit:
      $ref: "./schema/edit.json"
    Error:
      $ref: "./schema/error.json"
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example: { "error": "specified id does not exist" }
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          examples: 
            Bad JSON:
              value: { "error": "malformed JSON" }
            Schema Error:
              value: { "error": "schema was not respected." }
    Options:
      description: No Content
      headers:
        Access-Control-Allow-Origin:
          $ref: "#/components/headers/Access-Control-Allow-Origin"
        Access-Control-Allow-Methods:
          $ref: "#/components/headers/Access-Control-Allow-Methods"
        Access-Control-Allow-Headers:
          $ref: "#/components/headers/Access-Control-Allow-Headers"
        Access-Control-Max-Age:
          $ref: "#/components/headers/Access-Control-Max-Age"
  headers:
    Access-Control-Allow-Origin:
      schema:
        type: string
      description: Allowed 'Origin'.
    Access-Control-Allow-Methods:
      schema:
        type: string
      description: Allowed HTTP Methods.
    Access-Control-Allow-Headers:
      schema:
        type: string
      description: Allowed HTTP Headers.
    Access-Control-Max-Age:
      schema:
        type: string
      description: Allowed number of seconds to cache the Preflight response.

paths:
  /users:
    get:
      tags:
        - Search
      summary: List of users
      responses:
        "200":
          description: OK
          headers:
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
              example:
                [
                  {
                    "id": 234,
                    "name": "John Doe",
                    "email": "john@example.com",
                  },
                  { "id": 89, "name": "Jane Doe", "email": "jane@example.com" },
                ]
    put:
      tags:
        - Edit
      summary: Create a new user
      requestBody:
        description: add a new user with given information
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Add"
            example: { "name": "John Doe", "email": "john@example.com" }
      responses:
        "201":
          description: Created
          headers:
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                { "id": 234, "name": "John Doe", "email": "john@example.com" }
        "400":
          $ref: "#/components/responses/BadRequest"
    options:
      tags:
        - CORS
      summary: Preflight check for CORS
      description: Descripe access to selected resources from a different origin
      responses:
        "204":
          $ref: "#/components/responses/Options"
  /users/{id}:
    parameters:
      - $ref: "#/components/parameters/id"
    get:
      tags:
        - Search
      summary: Display user
      responses:
        "200":
          description: OK
          headers:
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                { "id": 234, "name": "John Doe", "email": "john@example.com" }
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      tags:
        - Edit
      summary: Edit an existing user
      requestBody:
        description: edit any number of settings for a given user
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Edit"
            examples:
              name:
                value: { "name": "Jane Marry Doe" }
              email:
                value: { "email": "john.doe@example.com" }
              both:
                value:
                  { "name": "Jane Marry Doe", "email": "jane.doe@example.com" }
      responses:
        "202":
          description: Accpted
          headers:
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
              example:
                { "id": 234, "name": "John Doe", "email": "john@example.com" }
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - Edit
      summary: Remove an existing user
      responses:
        "204":
          description: No Content
        "404":
          $ref: "#/components/responses/NotFound"
    options:
      tags:
        - CORS
      summary: Preflight check for CORS
      description: Descripe access to selected resources from a different origin
      responses:
        "204":
          $ref: "#/components/responses/Options"
