name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install pip
      run: python -m pip install --upgrade pip

    - name: install conan
      run: |
        pip install conan
        conan remote add stiffstream https://api.bintray.com/conan/stiffstream/public

    - name: conan custom setup
      run: |
        git clone --single-branch -b dd/json-schema-validation https://github.com/prince-chrismc/conan-center-index.git recipes/json-schema-validator/all
        ls -la

    - name: install cmake
      uses: lukka/get-cmake@v3.17.1

    - name: configure
      run: |
        mkdir build
        cd build
        conan install ..
        cmake ..

    - name: make
      run: make
