name: C++ CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'backend/**'
      - '.github/workflows/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install pip
      run: python -m pip install --upgrade pip

    - name: cache conan data
      uses: actions/cache@v2
      with:
        path: ~/.conan/data
        key: ${{ runner.os }}-${{ hashFiles('**/conanfile.txt') }}

    - name: install conan
      run: |
        pip install conan
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: install cmake
      uses: lukka/get-cmake@v3.17.2

    - name: configure
      run: |
        cd backend
        mkdir build
        cd build
        conan install ..
        cmake ..

    - name: make
      run: |
        cd backend/build
        make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
         name: user_database_app
         path: backend/build/src/user_database_app

    - name: coverage
      run: |
        sudo apt-get install lcov
        cd backend/build
        cmake .. -DBUILD_TESTS=ON -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
        make user_tests coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: backend/build/coverage.info
        flag-name: cpp-backend-unit-test
        parallel: true
        parallel-finished: true
