name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - name: install pip
      run: python -m pip install --upgrade pip

    - name: install conan
      run: |
        pip install conan
        conan remote add stiffstream https://api.bintray.com/conan/stiffstream/public
        conan profile new default --detect
        conan profile update settings.compiler.libcxx=libstdc++11 default

    - name: conan custom setup
      run: |
        git clone --single-branch --depth=1 -b add/json-schema-validation https://github.com/prince-chrismc/conan-center-index.git
        cd conan-center-index/recipes/json-schema-validator/all
        conan create . 2.0.0@

    - name: install cmake
      uses: lukka/get-cmake@v3.17.1

    - name: configure
      run: |
        cd backend
        mkdir build
        cd build
        conan install ..
        cmake ..

    - name: make
      run: |
        cd backend/build
        make

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
         name: reactjs-from-cpp
         path: backend/build/reactjs-from-cpp

    - name: coverage
      run: |
        sudo apt-get install lcov
        cd backend/build
        cmake .. -DBUILD_TESTS=ON -DCOVERAGE=ON -DCMAKE_BUILD_TYPE=Debug
        make coverage

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v1.1.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: backend/build/coverage.info
