name: Documentation CI

on:
  push:
    branches: [ master ]
    paths: 
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      
    - name: Render OpenAPI
      run: |
        npx redoc-cli bundle api/openapi.yaml
        mkdir public 
        cp redoc-static.html public/index.html
   
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
        force_orphan: true
